project_name: kube-dash
release:
  github:
    owner: caarlos0
    name: kube-dash
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  binary: kdcli
  main: ./cmd/kdcli/main.go
  env:
  - CGO_ENABLED=0
- goos:
  - linux
  goarch:
  - amd64
  binary: kube-dash
  env:
  - CGO_ENABLED=0
  hooks:
    pre: packr
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
  - LICENSE*
  - README*
  - deployment.yaml
dockers:
  - binaries: ['kube-dash']
    image_templates:
    - 'caarlos0/kube-dash:{{ .Tag }}'
    - 'caarlos0/kube-dash:v{{ .Major }}.{{ .Minor }}'
    - 'caarlos0/kube-dash:latest'
