apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dash
  namespace: kube-system
  labels:
    app: kube-dash
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kube-dash
  template:
    metadata:
      labels:
        app: kube-dash
    spec:
      hostNetwork: true
      containers:
      - name: kube-dash
        image: caarlos0/kube-dash:latest
        resources:
          requests:
            cpu: "0.01"
            memory: "20Mi"
          limits:
            cpu: "0.1"
            memory: "20Mi"
