[[constraint]]
  name = "github.com/apex/log"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.3"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/tcnksm/go-input"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[prune]
  go-tests = true
  unused-packages = true
